<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Low Stock Alert - {{ $medicine->name }}</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
        }
        .header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 30px;
            text-align: center;
            border-radius: 10px 10px 0 0;
        }
        .content {
            background: #f8f9fa;
            padding: 30px;
            border-radius: 0 0 10px 10px;
        }
        .alert-box {
            background: #fff3cd;
            border: 1px solid #ffeaa7;
            border-radius: 8px;
            padding: 20px;
            margin: 20px 0;
        }
        .critical {
            background: #f8d7da;
            border-color: #f5c6cb;
        }
        .stats {
            display: flex;
            justify-content: space-between;
            margin: 20px 0;
        }
        .stat {
            text-align: center;
            flex: 1;
        }
        .stat-value {
            font-size: 24px;
            font-weight: bold;
            color: #e74c3c;
        }
        .stat-label {
            font-size: 12px;
            color: #666;
            text-transform: uppercase;
        }
        .action-button {
            background: #3498db;
            color: white;
            padding: 12px 24px;
            text-decoration: none;
            border-radius: 6px;
            display: inline-block;
            margin: 10px 5px;
        }
        .urgent {
            background: #e74c3c;
        }
        .footer {
            text-align: center;
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            color: #666;
            font-size: 12px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>🚨 Low Stock Alert</h1>
        <p>Immediate attention required for {{ $medicine->name }}</p>
    </div>
    
    <div class="content">
        <div class="alert-box {{ $urgency === 'critical' ? 'critical' : '' }}">
            <h2>{{ $medicine->name }} is running low!</h2>
            <p><strong>Current Stock:</strong> {{ $current_stock }} units</p>
            <p><strong>Reorder Level:</strong> {{ $reorder_level }} units</p>
            <p><strong>Urgency:</strong> {{ ucfirst($urgency) }}</p>
        </div>

        <div class="stats">
            <div class="stat">
                <div class="stat-value">{{ $current_stock }}</div>
                <div class="stat-label">Current Stock</div>
            </div>
            <div class="stat">
                <div class="stat-value">{{ $reorder_level }}</div>
                <div class="stat-label">Reorder Level</div>
            </div>
            <div class="stat">
                <div class="stat-value">{{ round((($reorder_level - $current_stock) / $reorder_level) * 100) }}%</div>
                <div class="stat-label">Below Target</div>
            </div>
        </div>

        <h3>Recommended Action:</h3>
        <p>{{ $suggested_action }}</p>

        <div style="text-align: center; margin: 30px 0;">
            <a href="{{ config('app.url') }}/automation/reorder-suggestions" class="action-button {{ $urgency === 'critical' ? 'urgent' : '' }}">
                View Reorder Suggestions
            </a>
            <a href="{{ config('app.url') }}/medicines/{{ $medicine->id }}" class="action-button">
                View Medicine Details
            </a>
        </div>

        <div style="background: #e8f4f8; padding: 15px; border-radius: 6px; margin: 20px 0;">
            <h4>💡 Smart Automation Tip:</h4>
            <p>Enable automatic reordering to prevent stockouts. Our AI can predict demand and suggest optimal order quantities.</p>
        </div>
    </div>

    <div class="footer">
        <p>This alert was generated by MediTrack Smart Automation System</p>
        <p>{{ now()->format('F j, Y \a\t g:i A') }}</p>
    </div>
</body>
</html>