<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Medicines Export</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }
        h1 {
            color: #333;
            border-bottom: 2px solid #4F46E5;
            padding-bottom: 10px;
        }
        .export-info {
            margin-bottom: 20px;
            color: #666;
            font-size: 14px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th {
            background-color: #4F46E5;
            color: white;
            padding: 12px;
            text-align: left;
            font-weight: bold;
        }
        td {
            padding: 10px;
            border-bottom: 1px solid #ddd;
        }
        tr:hover {
            background-color: #f5f5f5;
        }
        .stock-low {
            color: #F59E0B;
            font-weight: bold;
        }
        .stock-out {
            color: #EF4444;
            font-weight: bold;
        }
        .stock-ok {
            color: #10B981;
        }
        @media print {
            body {
                margin: 0;
            }
            .no-print {
                display: none;
            }
        }
    </style>
</head>
<body>
    <h1>Medicines Inventory Report</h1>
    
    <div class="export-info">
        <strong>Export Date:</strong> {{ $exportDate }}<br>
        <strong>Total Medicines:</strong> {{ count($medicines) }}
    </div>
    
    <button class="no-print" onclick="window.print()" style="padding: 10px 20px; background: #4F46E5; color: white; border: none; border-radius: 5px; cursor: pointer; margin-bottom: 20px;">
        Print / Save as PDF
    </button>
    
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Brand</th>
                <th>Category</th>
                <th>Stock</th>
                @if($canViewCosts)
                    <th>Cost Price</th>
                    <th>Selling Price</th>
                @endif
                <th>Expiry Date</th>
                <th>Batch Number</th>
            </tr>
        </thead>
        <tbody>
            @foreach($medicines as $medicine)
                <tr>
                    <td>{{ $medicine->id }}</td>
                    <td>{{ $medicine->name }}</td>
                    <td>{{ $medicine->brand ?? 'N/A' }}</td>
                    <td>{{ $medicine->category ?? 'N/A' }}</td>
                    <td class="
                        @if($medicine->stock == 0) stock-out
                        @elseif($medicine->stock <= $medicine->reorder_level) stock-low
                        @else stock-ok
                        @endif
                    ">
                        {{ $medicine->stock }}
                    </td>
                    @if($canViewCosts)
                        <td>UGX {{ number_format($medicine->cost_price, 0) }}</td>
                        <td>UGX {{ number_format($medicine->selling_price, 0) }}</td>
                    @endif
                    <td>{{ $medicine->expiry_date ? date('Y-m-d', strtotime($medicine->expiry_date)) : 'N/A' }}</td>
                    <td>{{ $medicine->batch_number ?? 'N/A' }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>
    
    <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #ddd; color: #666; font-size: 12px;">
        <p>Generated by MediTrack Pharmacy Management System</p>
    </div>
</body>
</html>